# Generated by Django 5.2 on 2025-04-29 15:16

from django.db import migrations

def create_initial_data(apps, schema_editor):
    Status = apps.get_model('dds', 'Status')
    Type = apps.get_model('dds', 'Type')
    Category = apps.get_model('dds', 'Category')
    Subcategory = apps.get_model('dds', 'Subcategory')

    statuses = ['Бизнес', 'Личное', 'Налог']
    for name in statuses:
        Status.objects.get_or_create(name=name)

    types = ['Пополнение', 'Списание']
    type_objects = {}
    for name in types:
        type_obj, _ = Type.objects.get_or_create(name=name)
        type_objects[name] = type_obj

    categories = [
        ('Маркетинг', 'Списание'),
        ('Инфраструктура', 'Списание'),
    ]
    category_objects = {}
    for name, type_name in categories:
        category_obj, _ = Category.objects.get_or_create(
            name=name,
            type=type_objects[type_name]
        )
        category_objects[name] = category_obj

    subcategories = [
        ('Farpost', 'Маркетинг'),
        ('Avito', 'Маркетинг'),
        ('VPS', 'Инфраструктура'),
        ('Proxy', 'Инфраструктура'),
    ]
    for name, category_name in subcategories:
        Subcategory.objects.get_or_create(
            name=name,
            category=category_objects[category_name]
        )

class Migration(migrations.Migration):
    dependencies = [
        ("dds", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_initial_data),
    ]
